version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres/databases.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
  accounts:
    build:
      dockerfile: ./backend/apps/accounts/Dockerfile
      context: .
      target: dev
    container_name: accounts
    image: accounts
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend/:/usr/src/app/
      - /backend/node_modules/:/usr/src/app/node_modules/
    env_file:
      - ./backend/apps/accounts/.env
    ports:
      - 3000:3000
    networks:
      - backend
  publications:
    build:
      dockerfile: ./backend/apps/publications/Dockerfile
      context: .
      target: dev
    container_name: publications
    image: publications
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend/:/usr/src/app/
      - ./backend/node_modules/:/usr/src/app/node_modules/
    env_file:
      - ./backend/apps/publications/.env
    ports:
      - 3001:3000
    networks:
      - backend
  app:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
      target: development
    container_name: app
    image: app
    restart: always
    volumes:
      - ./frontend/:/usr/src/app/
      - ./frontend/node_modules:/usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - 8080:3000
    networks:
      - backend
networks:
  backend:
    driver: bridge
