version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres/databases.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
  accounts:
    platform: linux/amd64
    build:
      dockerfile: ./backend/apps/accounts/Dockerfile
      context: .
      target: dev
    container_name: accounts
    image: accounts
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/apps/accounts/.env
    ports:
      - 3000:3000
    networks:
      - backend
networks:
  backend:
    driver: bridge
